//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelDepartment.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IDOrder { get; set; }
        public int IDEmployee { get; set; }
        public System.DateTime DateOrder { get; set; }
        public string NumberOrder { get; set; }
        public int IDTypeOrder { get; set; }
        public int IDPost { get; set; }
        public int IDDepartment { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Post Post { get; set; }
        public virtual TypeOrder TypeOrder { get; set; }
    }
}
