//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelDepartment.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public int IDPassport { get; set; }
        public int IDEmployee { get; set; }
        public string Series { get; set; }
        public string Number { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public string PlaceOfIssue { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
